/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vision;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class GUIPetShop extends javax.swing.JFrame {

    model.PetShop ps = new model.PetShop();
    
    public void cadastrar(){
        ps.setIdadeAnimal(Integer.parseInt(jtfIdadeDoAnimal.getText()));
        ps.setNomeAnimal(jtfNomeAnimal.getText());
        ps.setPesoAnimal(Double.parseDouble(jtfPesoDoAnimal.getText()));
        ps.setSexoAnimal(buttonGroupSexoAnimal.getSelection().getActionCommand());
        ps.setValorPrimeiroServico(Double.parseDouble(jtfServico1.getText()));
        ps.setValorSegundoServico(Double.parseDouble(jtfServico2.getText()));
        if(jckNfEmail.isSelected()){
            ps.adicionar(jckNfEmail.getText());
        }
        if(jckNfSms.isSelected()){
            ps.adicionar(jckNfSms.getText());
        }
        JOptionPane.showMessageDialog(null, "Dados cadastrados: "+ps+" Total a pagar de serviços R$ "+ps.calcularServicos(), 
                "Fechamento de caixa",JOptionPane.WARNING_MESSAGE );
    }
    public void cancelar(){
        jtfIdadeDoAnimal.setText(null);
        jtfNomeAnimal.setText(null);
        jtfPesoDoAnimal.setText(null);
        jtfServico1.setText(null);
        jtfServico2.setText(null);
        jrbMacho.setSelected(true);
        jckNfEmail.setSelected(false);
        jckNfSms.setSelected(false);
    }
    /**
     * Creates new form GUIPetShop
     */
    public GUIPetShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexoAnimal = new javax.swing.ButtonGroup();
        jPanelSuperior = new javax.swing.JPanel();
        jlNomeAnimal = new javax.swing.JLabel();
        jtfNomeAnimal = new javax.swing.JTextField();
        jlPesoAnimal = new javax.swing.JLabel();
        jtfPesoDoAnimal = new javax.swing.JTextField();
        jlIdadeDoAnimal = new javax.swing.JLabel();
        jtfIdadeDoAnimal = new javax.swing.JTextField();
        jrbMacho = new javax.swing.JRadioButton();
        jrbFemea = new javax.swing.JRadioButton();
        jPanelInferior = new javax.swing.JPanel();
        jlServico1 = new javax.swing.JLabel();
        jlServico2 = new javax.swing.JLabel();
        jtfServico1 = new javax.swing.JTextField();
        jtfServico2 = new javax.swing.JTextField();
        jckNfEmail = new javax.swing.JCheckBox();
        jckNfSms = new javax.swing.JCheckBox();
        jbCadastrar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSuperior.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação do animal"));

        jlNomeAnimal.setText("Nome do animal:");

        jlPesoAnimal.setText("Peso do animal:");

        jlIdadeDoAnimal.setText("Idade do Animal:");

        buttonGroupSexoAnimal.add(jrbMacho);
        jrbMacho.setSelected(true);
        jrbMacho.setText("Macho");
        jrbMacho.setActionCommand("Macho");

        buttonGroupSexoAnimal.add(jrbFemea);
        jrbFemea.setText("Fêmea");
        jrbFemea.setActionCommand("Fêmea");

        javax.swing.GroupLayout jPanelSuperiorLayout = new javax.swing.GroupLayout(jPanelSuperior);
        jPanelSuperior.setLayout(jPanelSuperiorLayout);
        jPanelSuperiorLayout.setHorizontalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlIdadeDoAnimal)
                    .addComponent(jlPesoAnimal)
                    .addComponent(jlNomeAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                        .addComponent(jtfIdadeDoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(jrbMacho))
                    .addComponent(jtfPesoDoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jrbFemea)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSuperiorLayout.setVerticalGroup(
            jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSuperiorLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeAnimal)
                    .addComponent(jtfNomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesoAnimal)
                    .addComponent(jtfPesoDoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdadeDoAnimal)
                    .addComponent(jtfIdadeDoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbMacho)
                    .addComponent(jrbFemea))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanelInferior.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços"));

        jlServico1.setText("Serviço 1, valor:");

        jlServico2.setText("Serviço 2, valor:");

        jckNfEmail.setText("Enviar NF por e-mail");

        jckNfSms.setText("Enviar NF por SMS");

        javax.swing.GroupLayout jPanelInferiorLayout = new javax.swing.GroupLayout(jPanelInferior);
        jPanelInferior.setLayout(jPanelInferiorLayout);
        jPanelInferiorLayout.setHorizontalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInferiorLayout.createSequentialGroup()
                        .addComponent(jlServico2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfServico2))
                    .addGroup(jPanelInferiorLayout.createSequentialGroup()
                        .addComponent(jlServico1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfServico1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(263, 263, 263)
                .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jckNfEmail)
                    .addComponent(jckNfSms))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanelInferiorLayout.setVerticalGroup(
            jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInferiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlServico1)
                    .addComponent(jtfServico1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jckNfEmail))
                .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInferiorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlServico2)
                            .addComponent(jtfServico2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInferiorLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jckNfSms)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jbCadastrar)
                        .addGap(100, 100, 100)
                        .addComponent(jbCancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbCancelar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPetShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPetShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexoAnimal;
    private javax.swing.JPanel jPanelInferior;
    private javax.swing.JPanel jPanelSuperior;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JCheckBox jckNfEmail;
    private javax.swing.JCheckBox jckNfSms;
    private javax.swing.JLabel jlIdadeDoAnimal;
    private javax.swing.JLabel jlNomeAnimal;
    private javax.swing.JLabel jlPesoAnimal;
    private javax.swing.JLabel jlServico1;
    private javax.swing.JLabel jlServico2;
    private javax.swing.JRadioButton jrbFemea;
    private javax.swing.JRadioButton jrbMacho;
    private javax.swing.JTextField jtfIdadeDoAnimal;
    private javax.swing.JTextField jtfNomeAnimal;
    private javax.swing.JTextField jtfPesoDoAnimal;
    private javax.swing.JTextField jtfServico1;
    private javax.swing.JTextField jtfServico2;
    // End of variables declaration//GEN-END:variables
}
